name: Experimental JUnit 5 build

on:
  push:
    branches: 'master'
    tags-ignore:
      - 'v**'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        junit5Minor: [ '5.0', '5.1', '5.2', '6.0', '6.1', '6.2' ]
    name: with JUnit 5.${{ matrix.junit5Minor }} on ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@release
        name: Gradle build
        with:
          job-id: jdk11
          arguments: --refresh-dependencies --stacktrace --scan clean build -PjunitMinorVersion=${{ matrix.junit5Minor }}
          multi-cache-repository: https://oss.sonatype.org/content/repositories/comgithubburrunan-1010
